//
// Created by Jennifer Langford on 3/24/22 for Week 1 Assignment - Executing Your
// First C++ Program - SDEV-240-45
//This a basic assignment, designed essentially to ensure that you have your IDE
// properly installed, and that you can execute C++ code.
//
//Write a program that creates two integer values.
//Assign two values to them.
//Send the result of adding them to the standard output.
//Upload two files: the .cpp file generated by the IDE, and a screenshot of the execution.
//
#include "std_lib_facilities.h"

int main()  // C++ programs start by executing the function main
{
    int integer1 = 5; //First integer value assigned
    int integer2 = 2; //Second integer value assigned
    cout << integer1 + integer2; //result of sum value to standard output 
}
